export const questionList = [{
    questionText: "Are you looking to study, socialize, or relax and recharge?",
    option1: "Study",
    option2: "Socialize",
    option3: "Relax and Recharge"
}, {
    questionText: "Are you looking for someplace loud, quiet, or a mix?",
    option1: "Loud",
    option2: "Quiet",
    option3: "Mix of Both"
}, {
    questionText: "How hungry are you?",
    option1: "I'm VERY hungry!",
    option2: "I could use some food",
    option3: "Not hungry at all"
}, {
    questionText: "What environment would you like to be in?",
    option1: "Indoors",
    option2: "Outdoors",
    option3: "Easy access to both"
}];

export const resultList = new Map([
    ["aaaa", "Squarrel Cafe"], 
    ["aaab", "Coney Island Beach and Boardwalk"], 
    ["aaac", "Squarrel Cafe"], 
    ["aaba", "Blue Note Jazz"], 
    ["aabb", "Prospect Park"], 
    ["aabc", "Prospect Park"], 
    ["aaca", "Blue Note Jazz"], 
    ["aacb", "Prospect Park"], 
    ["aacc", "Squarrel Cafe"], 
    ["abaa", "Squarrel Cafe"], 
    ["abab", "Prospect Park"], 
    ["abac", "Squarrel Cafe"], 
    ["abba", "The Metropolitan Museum of Art"], 
    ["abbb", "Prospect Park"], 
    ["abbc", "Prospect Park"], 
    ["abca", "The Metropolitan Museum of Art"], 
    ["abcb", "Prospect Park"], 
    ["abcc", "Squarrel Cafe"], 
    ["acaa", "Nuyorican Poets Cafe"], 
    ["acab", "Prospect Park"], 
    ["acac", "Squarrel Cafe"], 
    ["acba", "Squarrel Cafe"], 
    ["acbb", "Prospect Park"], 
    ["acbc", "Prospect Park"], 
    ["acca", "Squarrel Cafe"], 
    ["accb", "The High Line"], 
    ["accc", "Squarrel Cafe"], 
    ["baaa", "The Village Underground"], 
    ["baab", "Coney Island Beach and Boardwalk"], 
    ["baac", "The Stand NYC"], 
    ["baba", "The Village Underground"], 
    ["babb", "The High Line"], 
    ["babc", "Prospect Park"], 
    ["baca", "The Village Underground"], 
    ["bacb", "The High Line"], 
    ["bacc", "The Stand NYC"], 
    ["bbaa", "Squarrel Cafe"], 
    ["bbab", "The High Line"], 
    ["bbac", "The High Line"], 
    ["bbba", "The Metropolitan Museum of Art"], 
    ["bbbb", "The High Line"], 
    ["bbbc", "Prospect Park"], 
    ["bbca", "The Metropolitan Museum of Art"], 
    ["bbcb", "The High Line"], 
    ["bbcc", "The High Line"], 
    ["bcaa", "Nuyorican Poets Cafe"], 
    ["bcab", "The High Line"], 
    ["bcac", "The High Line"], 
    ["bcba", "Squarrel Cafe"], 
    ["bcbb", "Prospect Park"], 
    ["bcbc", "Prospect Park"], 
    ["bcca", "Squarrel Cafe"], 
    ["bccb", "The High Line"], 
    ["bccc", "Prospect Park"], 
    ["caaa", "The Village Underground"], 
    ["caab", "Coney Island Beach and Boardwalk"], 
    ["caac", "The Village Underground"], 
    ["caba", "Blue Note Jazz"], 
    ["cabb", "Prospect Park"], 
    ["cabc", "Prospect Park"], 
    ["caca", "Blue Note Jazz"], 
    ["cacb", "Prospect Park"], 
    ["cacc", "The Village Underground"], 
    ["cbaa", "The Village Underground"], 
    ["cbab", "The High Line"], 
    ["cbac", "The Village Underground"], 
    ["cbba", "The Metropolitan Museum of Art"], 
    ["cbbb", "The High Line"], 
    ["cbbc", "Prospect Park"], 
    ["cbca", "The Metropolitan Museum of Art"], 
    ["cbcb", "The High Line"], 
    ["cbcc", "Brooklyn Museum"], 
    ["ccaa", "Nuyorican Poets Cafe"], 
    ["ccab", "Prospect Park"], 
    ["ccac", "The Stand NYC"], 
    ["ccba", "Blue Note Jazz"], 
    ["ccbb", "Prospect Park"], 
    ["ccbc", "Prospect Park"], 
    ["ccca", "Blue Note Jazz"], 
    ["cccb", "The High Line"], 
    ["cccc", "The Stand NYC"]
  ]);